---
title: Leo Breiman 访谈实录
author: 张晔 成慧敏 李宇轩
output: html_document
---

###摘要


1928年1月28日，Leo Breiman诞生于纽约，在他出生5年后他们全家移民去了旧金山，在这里他开始了学业生活。在他读初中的时候，他们全家又移民到了洛杉矶。1945年，Leo从Roosevelt高中毕业后考进了加州理工学院，在加州理工学院他花了4年时间主修物理。1950年，Leo拿到了哥伦比亚大学的数学系硕士学位，1954年，他又拿到了加州大学伯克利分校的数学系博士毕业学位。


Leo对科学和数学有着广泛的兴趣，包括信息论和博弈论。他曾参与研究汽车交通，空气质量和有毒物质的识别。
他写过一篇著名的有关概率论的毕业论文，是分类回归树及其配套软件CARTR的四大作者之一，另外他还写了两本其他的书。Leo和Jerome Friedman一起发展了ACE（alternating conditional expectations）算法，该算法描述了因变量和自变量之间的非线性回归关系。
他开创性地将 "bagging" 和 "arcing" 这两种需要大量计算的方法用于分类，目前很多人对此十分感兴趣。



Leo的职业生涯经历了UCLA数学系的任教，13年的独立咨询顾问，在加州大学伯克利分校统计系的教授和统计计算设施的创始主任。
而且，他还是斯坦福和耶鲁大学的客座教授。
由于他的诸多贡献，Leo被授予数理统计研究所（Institute of
Mathematical Statistics ）和美国统计协会（American Statistical Association）的荣誉奖学金。
同时，他还当选美国艺术与科学学院（American Academy of Arts and Sciences）的成员，并被加州大学授予 Berkeley Citation荣誉奖项。


Leo Breiman的兴趣和成就不只限于专业的统计学家和概率学家
他在Catskills当过服务员，在Merchant Marine当过洗碗工，还是探寻过热带雨林之心的背包客，是一群来自墨西哥农村孩子的慈爱父亲，是Santa Monica学校董事会的主席，是他美丽小屋的建筑师，同时还是一个技艺高超的雕刻家。 Leo和他的妻子Mary Lou，居住在伯克利（Berkeley），他们育有两个女儿，Rebecca和Jessica。


采访者简介：Richard Olshen，是斯坦福大学生物统计教授，生物统计科（Division of Biostatistic）主任，卫生研究和政策系（Department of Health Research and Policy）的副主席，电气工程与统计系教授。

该访谈于1999年2月19日在Leo和他的妻子Mary Lou Breiman家中进行。

###正文
**Olshen**：
Leo,今天在这里我感到非常荣幸。我是您的一枚粉丝，在跟您合作之前（事实上，是我认识您之前）我从您的著作中学习到了很多。我了解到您是在洛杉矶的Boyle Heights长大的，Boyle Heights那个时候是什么样的？

###BOYLE HEIGHTS
**Breiman**：
Boyle Heights那时候还是个贫穷的犹太人区，工人阶级的犹太人贫民区，与墨西哥贫民区相邻。基本上，它是第一代移民的贫民区。我的父母，那里其他人的父母也是移民。

而且我们都是去罗斯福（Roosevelt）高中上学，这所高中致力把移民的后代培养成医生、律师和科学家。
这是一个很美好的地方。
你可以走进一家熟食店，从泡菜桶里拿出泡菜，然后沿着街道一直走，可以比人晾晒看到意大利腊肠（salamis）。意大利腊肠（salamis）是来自纽约下东区（纽约市曼哈顿区沿东河南端一带，犹太移民聚居地）有点高档的食品。


**Olshen**: 也许还有更好的天气


**Breiman**：是的 



**Olshen**: 你什么时候把对数学和科学的兴趣结合起来的呢？


**Breiman**：我在高中的时候对几何感兴趣，因为几何是第一门让我印象深刻的科目。
你知道吗，当你解决完代数或者加上数字之类的问题之后，挑战几何问题是一件全然不同而且令人着迷的事，以至于我们一群人在研究它的时候根本停不下来。


**Olshen**: 关于罗斯福（Roosevelt）高中所在的社区你还有什么其他的能告诉我们的吗？是什么促使你对加州理工学院(Caltech)感兴趣并真正加入加州理工学院的呢？

**Breiman**：嗯，虽然罗斯福(Roosevelt)社区那时候是洛杉矶最穷的社会经济社区之一，但罗斯福高中是一流的学术高中之一。
这个原因也许和Bronx科学高中的原因是一样的。

这里充满了有激情的移民家庭的儿女，大家都明确地知道一定要上大学。
而激发我去加州理工学院(Caltech)的原因，是我母亲听说加州理工学院是西方最好的科学性学校，于是她决定她儿子应该去加州理工学院。


**Olshen**: 你有兄弟姐妹吗？


**Breiman**：没有



**Olshen**: 所以唯一的儿子干什么真的非常重要


**Breiman**：是的

###加州理工学院(Caltech) 

**Olshen**: 能跟我讲一下你还在加州理工学院的时候，那儿是什么样的吗？

**Breiman**：当然。那年申请加州理工学院的几千人，但是最终录取的只有250人。为了能被录取，你必须参与16个小时的考试，因为他们完全不相信高中成绩。
你必须考数学、物理、化学和英语四科，每科考四小时，而且我们需要把它们都写出来。

在加州理工学院的第一年，我确实表现得很好，也拿到了奖学金。但是第二、三、四年，我变得越来越烦闷，我厌倦了每天听到的不是科学就是电气，这让我开始封闭起来。这个地方就像是一个科学修道院。

所以，我的成绩开始急剧下滑，在我最后一年时，我的主修科目物理得到了4个D。



**Olshen**: 这是让你去加州大学伯克利分校研究生院的原因吗？


**Breiman**：不是，实际上是虽然我毕业时的物理成绩太差了，但是我还是对数学很感兴趣。我在数学方面很好，我到处申请，最终只有纽约的哥伦比亚大学接收了我。我的父母十分贫穷，而且没法承担我在哥大的学费。

但是由于之前我打工存了一些钱，所以我最终还是有能力去哥大的。然后我用1年的时间在哥大获得了数学硕士学位，但是实际上我最开始去哥大时是想主修哲学的。

当我到了这之后，我和赫赫有名的哲学系系主任Erwin Edwin交谈了一番。他语重心长地拍了拍我，说道，“你看，我两个最优秀的博士生现在都没找到工作。你为什么不待在数学系，然后上一些哲学系的课看看呢？”

然后我就上了一些哲学系的课，比如说美学和希腊哲学等等。
最终，我还是决定回归到了数学。


**Olshen**: 能告诉我们具体的时间吗？


**Breiman**：那是1950年的时候，我从哥大拿到硕士毕业学位1年之后，我申请了伯克利的数学系，他们接受了我。为了能支付学费，我1个暑假在Catskills（卡次启尔山脉，位于纽约的南部）当服务员打暑假工，另一个暑假在美国商船学院（Merchant Marine）。


**Olshen**: 美国商船学院（Merchant Marine）听起来很不错


###毕业于伯克利


**Breiman**：是的，在我20岁之前，我这样打工挣了很多钱。我在船上当洗碗工，一下船就得去监考，监考是所有伯克利助教必须干的事。从码头叫了一辆出租车，我迅速地奔向大一新生考试的地方Dwinelle，所以—



**Olshen**: 所以你的航海生涯和数学生涯交错进行？



**Breiman**：确实是


**Olshen**: 棒极了，能跟我们讲讲David Blackwell对你的影响吗？还有其他跟你一起在伯克利学习的人也可以讲讲吗？我其实是想问的是和这两个主题相关的：一个是Shannon–Breiman–MacMillan理论(Breiman,
1957)，另外一个是你博彩系统相关的工作(Breiman, 1960)。


**Breiman**：好的，我当时是在伯克利的数学系，那会儿还没有独立的统计系。那个时候，Neyman想引入一些人，比如 Michel Loève è 。当时，我上的概率论这门课是教的，我非常喜欢这门课，我喜欢概率论。

这是一门很好的课程，一门大概只有10个人左右的课程。Manny Parzen也在这个课堂里，还有Howard Tucker，还有一两个后来在统计界声名远扬的人。然后我写了一篇论文，但是 Michel Loève è 是一个完美主义者，他让我在论文上不断下功夫。



**Olshen**: 我情不自禁地想起来，当我大一刚入学时，我的导师是Michel Loève è ，他在办公室对我说的第一句话就是，"你最好全部课程都得A，不然我会把你从窗户扔出去。"

**Breiman**：这听起来很像是Michel的风格，所以每次我写完论文觉得这已经很不错的时候，Michel都会说“我不知道”。然后，Harold Cram´er来到了伯克利一学期，我在他组织的研讨会上提交了我的论文结果。

他说，“我必须跟Michel好好谈谈，我觉得这篇论文已经很不错了”。
但是，这时候一件更加重要的事情发生了，我收到了一个来自征兵局的通知，通知上说“注意！你已经用尽了所有的延期时间，我们希望在30天之后在这里看到你”

所以我给Michel提交了我最新一版论文的复件，同时把那个征兵局的通知也放在上面。Michel盯着它看了很久，然后说，“好吧，我们必须让你尽快离开这里了”。大概在两周之后，他组织了论文的最后答辩，然后我的论文获得了批准，我当时很激动。离开伯克利之后，我服役了将近两年。



**Olshen**: 等一下，让我们回过头看之前的问题。你的毕业论文和Shannon–Breiman–MacMillan理论有关，还是和你的博彩系统有关呢？



**Breiman**：不是的，当时军队有个规定是，如果你能找到工作，你就可以提前两个月出去，我写信给Neyman教授，他给了我一个代理助理教授的工作，于是我就回来了，也就是那个时候我开始结识了David Blackwell。

我们那个时候一起开研讨会，他经常拿一些笔记来问我，“你会证明这个、这个和这个吗？”
有一次，他给的一个笔记上写着，“你能证明这个几乎收敛于下面的式子吗？”
我想了好些天，然后我觉得我可以做到，我觉得我已经有思路了，Shannon–Breiman–McMillan理论(Breiman, 1957)就是这么诞生的。和Dave Blackwell一起工作十分的鼓舞人心，他思考问题的方式真的非常了不起。



**Olshen**: 是Dave Blackwell促使你进入博彩这个领域的吗？


**Breiman**：不是的，完全是因为我自己。我当时在思考凯利指数。



**Olshen**: 跟我讲讲怎么回事


**Breiman**：凯利指数大概是说，如果你在一个有利的赌局中下赌注，你就可以赢得无穷多的钱。这也不是一定的，但是至少你的期望收益会是无穷的。我思考了一下凯利指数，然后我意识到他们其实是在采取最优策略来玩一局有利于自己的赌局。

这是我研究博彩的动机，完全是因为机缘巧合。David 没有参与进来，而且我觉得他应该对博彩业不感兴趣。

###在墨西哥卖冰

**Olshen**: 大家都知道你涉猎广泛，其中你在墨西哥卖冰那件事非常吸引我，但是我到现在也不太清楚，你能跟我讲讲那个吗？

**Breiman**：好的，实际上那是因为我的几个朋友在1964年或者1965年去了Puerto
Vallarta，具体年份我记不太清楚了，但是正好就是在Night of the Iguana(译者注：即《巫山风雨夜》，1964年上映的电影)这部电影上映之后的一年。
当时，Puerto
Vallarta还只是一个小城镇，你需要把你所有的水都煮沸才行。

另外一件你需要注意的事就是，如果有人在你的饮料中加了冰块，千万不要喝。
因为当地的冰块都是用当地的水做的，都充满了细菌。所以我的朋友就想出了一个点子：把
纯化的制冰机送到墨西哥，并且建立一个专门净化冰的工厂，这个想法同样让我觉得很感兴趣。

我觉得这很棒，我说，“我也要投资”。接下来他们买了一栋旧得几乎摇摇欲坠的建筑，叫做El Bucanero。
他们在这里建立起了冰厂，这是一个伟大的成功。然后这个厂净化出来的冰在Puerto Vallarta远近皆知，因为他们从冰的中间把杂质吸出来，所以看起来像一个甜甜圈。在Puerto Vallarta，无论你走到哪，你都可以看到一杯装有甜甜圈冰块的饮料。没多久，市长的儿子也决定开始做净化冰的生意。
果然，我们所有的顾客都跑去光顾市长儿子的生意了。所以我们的生意就黄了，但是净化冰这件事持续下来了，这非常伟大。

**Olshen**: 听起来很棒

**Breiman**：嗯，是的。

###在UCLA的那几年



**Olshen**: 现在我要继续和你谈谈你在UCLA的职业生涯了，其实我是想问一些我一直非常想知道的事。
就是你怎么想到写probability (Breiman,1968)这本伟大的书的呢？

**Breiman**：我进入UCLA是因为，我在伯克利只有一份署理职位（译者注：署理职位一般不能超过6个月）。
那时的规则非常严格，如果你是一名伯克利的博士生，那么你铁定不能在伯克利找到你的第一份工作。那么接下来对我来说，去UCLA对似乎是最好的选择了。

所以我走在街上，并进入了数学系说，“我是来求职的”。他们收到了一些关于我的信件，然后我获得了一份工作。我在这儿一待就待了7年，实际上我很快就拿到了终身教授的职位。我是他们唯一的一名概率学家，所以
我教研究生概率论的课程，教了大概3到4年。

在整个教学过程中，我一直专注于概率论中的证明，直到搞懂内在的原理。

在UCLA待了大概7年之后，我对我自己说，“Leo,你天生就不是做抽象数学家的料，它虽然很有趣，但不是你该做的工作。”于是，我辞职了。

**Olshen**: 到那时，你已经写了这本书了吗？


**Breiman**：还没有



**Olshen**: 那个时候还没有吗？



**Breiman**：没有



**Olshen**: 好吧

**Breiman**：所以我拿出了放在我退休金中的钱，然后我花了6个月时间专门来写这本书。
这是相当长的一段时间，因为写这本书需要很强的纪律性。
但是同时这个过程又充满了乐趣，它是我的处女作。

因此，当3、4年前SIAM([美国]工业及应用数学学会) 找到我说，“我们想在经典系列中再版你的书”时，我喜出望外。


**Olshen**: 我听说你在UCLA工作期间，还去了非洲。


**Breiman**：是的，确实是这样。我想要一个不同寻常的休假，所以我去了联合国教科文组织（UNESCO），然后我对他们说，“我不想在大学里教书，你们能给我什么其他的呢？”
最后联合国教科文组织告诉我，“我们有一个在利比亚（Liberia）当教育统计学家的机会给你。”

所以我就以一名教育统计学家的身份去了利比亚，那么他们需要什么呢？他们需要知道全国所有学校里的学生有多少人。为什么这会是个难题呢？因为整个国家只有50英里铺设好的道路。很多学校都在热带雨林丛林里，这些地方看起来根本没法进入。所以我们组了大概20支队伍，以骑车、划船和走路的方式走遍全国，深入到那些小村庄，把学校里的孩子们都叫出来，然后数一下人数。

所以我住在这里，艰苦跋涉去了很多边远地区，经过了热带雨林丛林中通往村庄的隧道。
很神奇的是，当我到达村庄的时候，小孩子们会过来搓我的皮肤，看看能不能把我皮肤上的白色搓下来。
那是一种非常有趣的体验，我几乎爱上了在非洲的生活，而且很遗憾要离开这里。



**Olshen**: 跟我讲讲你与Bill Meisel的合作，以及你是如何去TSC（技术服务公司）工作的

###一名独立的顾问

**Breiman**：从UCLA辞职之后，我开始花我的退休金，很显然我需要干一些别的事业来养活我自己。
所以我四处询问，当时Rand旗下的SDC系统发展公司，有一大笔联邦资金用于研究高速公路交通。

我之前写过一篇关于交通流量服从泊松分布的文章(Breiman, 1963)，而且我认识一个在交通研究工作的人，他对我说，“你为什么不给SDC当咨询顾问呢？”所以接下来的一年我就给SDC当咨询顾问了。
研究高速公路交通流量数据长什么样以及它的统计特征是什么，是一件充满乐趣的事。

之后这笔联邦基金花完了，所以我又四处询问。另一位顾问Pete Payne告诉我，“我觉得TSC（技术服务公司）在招聘顾问。”所以我去TSC应聘，Bill Meisel面试了我。我们交谈了一会儿之后，他说，“OK，你被录用了，你什么时候可以开始呢？”Bill是一个十分有趣的人，因为他在USC工程系任教过。



**Olshen**: 你之前在加州理工学院的时候就认识他吗？



**Breiman**：不，完全不认识。他还写过一本关于模式识别的书。
TSC基本上是一个雷达室，一个防御室，不是一个很大的公司，里面大概就是50到60个技术人员。
Bill当时管理这种零碎的部门，然后他决定集中精力让它成为一个环保部门。

所以我开始给环保部门当顾问，我们两个开始写提案给EPA（Environmental Protection Agency，美国环保署）和加利福尼亚州空气污染董事会等。我们开始赢得了很多赞成和支持。
我开始做一些EPA赞助的空气污染工作、水污染工作和各种各样诸如此类的工作。
我们遇到的很多问题都涉及到大量的数据，比如说在一个大项目里我们有7年每天每小时的空气污染数据，涉及到450个和空气污染相关的变量。
我们尝试预测洛杉矶盆地第二天的臭氧浓度。

Bill非常有助于我思考分类和回归的问题。对于EPA和周围很多其他资助研究的地方来说，大多数的问题
都是预测和分类，这是一个热门领域。Bill对于这个领域有所了解，他推动我进入这个领域。


**Olshen**: 听起来这是CARTR(Breiman et al., 1984)的开始。


**Breiman**：是的，说的没错。我们在研究预测问题，比如说第二天洛杉矶盆地的臭氧浓度，
高速公路上的一氧化碳浓度，还有一些其他的研究，比如是否能识别出摩尔斯电码是从哪个手机上发送的（这是我们为间谍机构做的事）？或者我们能否通过声呐返回技术识别出潜水艇是俄罗斯的还是美国的？或者我们能否通过雷达回波技术识别出战舰是俄罗斯的还是美国的？很多这些问题都是迷人的分类问题。同时，
Bill对于几乎一切能看到的有趣的统计需求，他都提出建议方案。

比如，我们做的其中一项是Colorado刑事法庭的延迟研究，我们也为刑事法庭系统做了一些其它的工作。我也设计了一些调查来帮助EPA监督管理。

因此，从这一大堆工作中我对统计学有了更加深刻的认识，我学会了在尝试解决问题时，如何使用统计学和处理数据。这些回答了你的问题吗？
### 在SANTA MONICA参加校董事会和教数学

**Olshen**: 很好。现在看来，这些工作全部或者说很大一部分都是在 Santa Monica 进行的。我对你在 Santa Monica 进行的其他工作很好奇，比如说，Santa Monica 校董会，你是怎么参与其中的工作，还成为它的领导者的？

**Breiman**: 好的，让我从稍早一点说起。我的朋友和我刚知道这个 Puerto Vallarta 以北30英里的村子叫 Mezcalse. 尽管那时候我还只是个单身汉，但是我在照顾两三个孩子。他们是我朋友的孩子，我朋友去了沙特阿拉伯工作，他认为那里不适合带上小孩。


所以他们算是把孩子托付给我。其中一个是小男孩，两个年长一点的女孩带着他。我想找另一个男孩来平衡一下，但我找不到，因为没有哪家父母愿意把孩子交给我照顾。这时有人建议我，何不从 Mezcales 村那里收养一对墨西哥小男孩呢？


我经历了美墨两国的官僚主义地狱，但我还是排除万难让两个小孩和我住在同一屋檐下。那时我住在 Topanga Canyon. 他们和我的美国小孩一道上初级语法学校，这是巨大的成功。


我收养他们的一个理由是：这个村子里全是自耕农，而且只有旅游业一个大产业，所以学英语是这些孩子们摆脱自耕农的唯一出路。到那一年年底，这些孩子们已经可以用英语交谈了。


他们讲得非常流利。所以接下来的夏天，我让头两个孩子回到了他们父母身边，他们父母非常高兴，为我带来了另外三个。如此持续了7年，我总共养大了21个孩子。这时我对 Santa Monica 校区了解得非常清楚了。


而且，本地得老师都很喜欢我的墨西哥小孩，而且——


**Olshen**: 即使从 Topanga 峡谷到 Santa Monica 是长途旅程？



**Breiman**: 是的。我当时还是单身，当着顾问。所以我要非常小心地安排一切。不管怎样，我最后搬到了 Santa Monica，因为 Santa Monica 相关部门抓住我了。我的意思是，他们发现我其实住在 Topanga，那是洛杉矶校区。所以孩子们要去洛杉矶的学校，这可很不好。我听从一个住在 Santa Monita 的朋友的建议，送他们去 Santa Monica 上学。 他们去那个房子访问，发现了这个事实，然后他们告诉我——



**Olshen**: 他们是指？


**Breiman**: 他们是指 Santa Monica 校区的官员们。

**Olshen**: 明白。

**Breiman**: 他们告诉我：“要么你在30天内搬到 Santa Monica，要么这些孩子得退学。”所以我搬去了 Santa Monica. 我对这个校区已经了解得十分清楚了。

当我还在 UCLA 的时候，我已经认定，孩子们接受数学教育的方式错得一塌糊涂，他们惶恐地将数学看成一门可怕又无聊的科目，和他们身边的日常世界没有一点关系。所以我决定亲自教两个五年级生数学。我教的其中一个孩子在 UCLA ——他们有给情绪障碍的孩子开的实验学校——另一个在一所中上水平的学校，并且——


**Olshen**: 你为此付出很多吗？

**Breiman**: 不，不。相反我过得相当愉悦。孩子们也很快乐。我们玩了各种各样的游戏。他们并不知道他们在搞数学，但是他们在学习诸如如何玩战舰游戏。同时他们还学笛卡尔几何，学代数，总之他们在游戏的引导下学习各种复杂的东西。

并且，你知道吗，我们会玩这样的游戏：“好，那是多远？这堵墙多高？”孩子们就会猜，然后我试着绕着圈子问，“不爬上去，我们要怎样才能量出它到底有多高？”， 诸如此类。


一方面，我所有的孩子都在 Santa Monica 的学校上学，；另一方面，我对如何在语法学校教数学很感兴趣。这两个原因让我断定Santa Monica 校区需要我，所以我去参加了校董会竞选。

有趣的是，Santa Monica 认识我的人很少。当我跑去教师工会谋求背书，跟他们说的时候，他们回应：“我们挺喜欢你说的东西，但是我们不能支持你，因为你根本没有胜算。”而民主党也不支持我，因为他们说：“啊，你在这里没有缴费。”


但我非常努力，我发起了一个效果良好的选举宣传，我到处和人谈话，逐家逐户拜访，站在超市里派发传单。最后，令我自己和别人都大吃一惊的是，我获选了。


**Olshen**: 你是怎样当上主席的？


**Breiman**: 那时候，Santa Monica 校董会主要考虑本地商人。那时 Santa Monica 还是相当保守的一个城市。本地商人尊重我对教育感兴趣这个事实。所以他们先是提名我当副主席，而副主席会在下一年自动接任主席。但我必须说校董会的商人们对 Santa Monica 的教育质量有着真实诚挚的兴趣——比校董会部分政治人物和更多的激进派要真挚(存疑，这一句我没有理解)。


**Olshen**: 就你的写作以及在两间大学的教学还有你的私人事业的经验，你教了许多人。你有没有找到教育的一种通用的哲学主题或者精神，不论对 Santa Monica 的五年级生还是伯克利天才研究生都适用的那种。

或者说有没有什么不变的主题，这些主题是渗透到了你不同程度教学和你的写作中的？你刚才谈到了让数学变得有意思，并且让数学联系到我们周围的生活---


**Breiman**: 有的


**Olshen**: ——比如说？

**Breiman**: 让我仔细想想。和孩子们一起，我可以说确信找到他们学习数学失败的结症在于转化的过程，也就是说，他们无法把教给他们的乘法或者其他别的来自这个封闭小世界（指数学）的东西和他们现实的生活中实际的内容对应起来。

这和他们处理单词问题时的无能为力很相似。在单词问题里面，你所必须做的事情就是拿起英语，使用魔法词汇"令 x 等于"。换句话来说，你必须将英语文本翻译成数学。

我觉得那些数学很好的人就是那些可以将真实世界和数学世界对应起来，将我们说的话翻译成数学语言的人。我认为这贯穿了我所有级别的教学。我们从一个明确的问题开始，在进一步抽象之前我发觉我会先构思好解决整个问题的流程。在把问题变抽象之前，你要尝试把问题具体化。


###回到伯克利统计计算专业


**Olshen**: 谢谢，接下来，你是怎样来到伯克利的？还有，为什么会来？


**Breiman**: 在我当咨询顾问期间，令我讶异地，我获得回到（用我朋友的话来说， "改邪归正"）大学工作的工作机会。而我不是特别乐意。我在咨询行业工作得十分愉快。在其中我解决真正得问题，用数据工作，如此等等，都是我热爱的。


但有天我忽然接到 Peter Bickel 打来的一个电话， 他说：“你要不要来伯克利讲一个学期的课，搞个讨论班？”然后我说：“好。” 我确实那样做了,回到了伯克利,那是一段美好的时光。


之后，我回到洛杉矶，大约一年后，我接到另一个电话——我记得这次是 Dave Brillinger 打来的——说：“好了，你要不要来担任教职？”


现在看来，在那个时候，世界上只有一个地方可以说服我回去学术界，那就是伯克利。在这里，我完成了我的研究生工作，还有很多朋友，我爱这里，所以我回答他：“好。”


**Olshen**: 当你来到这里的时候，你是已经有一个创立统计计算专业的观点了吗？还是说，这个观点是你逐渐发展来的？告诉我关于这方面的事情，如何争取资源，你的领导以及在你眼中，它的未来会是怎样？


**Breiman**: 如果可以，先让我准备大约一分钟吧，Richard.



**Olshen**: 请。


**Breiman**: 因为，你看，当我离开大学的时候，某种意义上，我已经破釜沉舟，断了回大学的路，因为这些年，大概是13年，我都是一个咨询顾问，我应该只出了一本出版物，我的意思是，你不会给钱一个咨询顾问让他出书，你给钱他是让他解决问题的。


所以我觉得，伯克利居然给了我一个高级教职，这很不寻常啊。而且，你要知道，我从来都不知道这件事情他们是怎样操作的。好像没有人适合告诉我内情。我想有朝一日我会去问个水落石出的。

**Olshen**: 但这个任命还没有带来坏消息。也许随它去就好了。但请告诉我关于统计计算专业的事情。


**Breiman**: 事情是这样。我到伯克利的时候，系里所有的计算基本上都是在中央计算实验室楼下做完的。

**Olshen**: 埃文斯楼楼下？



**Breiman**: 就在埃文斯楼。他们有一个大的多核主机，我们系里只有一个小的 PDP-11 (译者注：一款DEC公司出售的16位微机)，它的主内存只有32kb，还有其他各种各样的问题。我记得我第一次去中央计算实验室。我问他们，“你们有什么统计包吗？”



然后他们说，“啊，我们貌似有 BMDP (译者注：由加州大学洛杉矶分校的 Wilfrid Dixon 开发的一个统计软件包)。不，我们没有整个包。我们只有一部分。”


然后我又说，“那好，你知道你们有哪些部分？”


最后他们说，“嗯，我们会去找找看。”

我原计划教多元分析。很显然，如果要计算各种数据的关联，我们系必须要有一个合适的计算实验室。埃文斯的地下室显示不适合。所以我说，“好，我要做的第一件事，就是建立一个足够好的计算实验室。”


那是1980年，我们可以买到的最好的微机是 VAX 750。它的售价在我们的价格范围内。它有一个16位系统，内存很多，打折之后仅售75,000美元。


**Olshen**: 你有来自学校当管理层的帮助吗？还是说全都是统计系的功劳？

**Breiman**: 都是统计系的功劳。我们没钱。


**Olsehn**: 嗯哼。


**Breiman**: 我所有的，只有手中咯咯作响的一只锡杯。


**Olshen**: 还有墨西哥的制冰机。


**Breiman**: 对。所以我开始到处打电话，看看能不能找到联邦机构为 VAX 提供资金。 最后我找到海军研究办公室(ONR)的 Ed Wegaman 。 我对他说，“Ed， 如果我们还想做一丁点应用研究，我们一定要有电脑。”


他问：“多少钱？”

我回答说：“75,000美元。”
.

他说：“好的。给我发一份计划书。” Ed 最后搞定了。那是我们第一台 VAX 。我们把他组装起来，招了个研究生做系统管理员。自此之后，事情变得轻松了——一旦你破开冰层，事情就变得简单了。获得许多捐款和赠送之后，我们现在每年有2,000账号，4个全职高级成员还有大量的计算资源。我们还支持经济学和生物统计的计算。


**Olshen**: 在你组建SCF的同时，伯克利 UNIX 小组也开始崭露头角。统计和伯克利 UNIX 小组之间有什么联系吗？，你会在你的 VAX 上跑 UNIX 或者 VAX。


**Breiman**: 关于这个有一些美妙的故事。我来伯克利的时候，David Freedman 还是主席。而 Dave ，我觉得他和我在伯克利就职有很大关系，因为他和我相互了解很久了。那时他还用我们的 PDP-11. Dava 被计算深深吸引住了。

PDP-11 当时运行着 UNIX，除非数学系的家伙有问题需要在 RISTUS 操作系统下解决（这是一种可以在 PDP-11 上跑的操作系统）。所以我们有个协议。4天跑 UNIX 三天跑 RISTUS。而 Dave Freedman， 每隔三天或者四天，就要去更换操作系统，重启电脑。


**Olshen**: 精彩！

**Breiman**: 对。

###CART, ACE, PIMPLE, THE LITTLE BOOTSTRAP, BAGGING, BOOSTING 和 ARCING

**Olshen**: 现在让我们继续吧。我想听听更多你近来对于科研的兴趣。不分顺序，我能想到的是 ACE (Breiman and Friedman, 1985), PIMPLE (Breiman, 1991), the little bootstrap (Breiman, 1992), bagging (Breiman, 1996a, 1996b), boosting (Freund and Schapire, 1996, 1997), arcing (Breiman, 1998), 和 CARTR。不管以后怎样，它们现在已经不是统计学的私房话了。


**Breiman**: 大概在我从 UCLA 退学开始吧，我认为最明显的就是你也参与其中的 CART ，那是非常激动人心的时期。所有的创意想法在你我还有 Jerry Friedman 和 Chuck Stone 之间来回碰撞。 


即便这样，CART 那本书(Breiman et al., 1984)出版后，我想我们全部——也许你不像其余三个那么严重——都厌倦了跟树相关的思考。我们一口气干得太多了，有点腻了。所以我们的兴趣转向了别的地方。但 Jerry 和我还在讨论。


Bill Meisel 把 Jerry 和我招进 TSC 当顾问。所以在我来伯克利之前，我熟悉 Jerry 好多年了。Jerry 和我继续讨论是因为我觉得我们是身边少数关心如何分析高维数据的统计学家。


我们其中一个话题，一个非常重要的问题——那是86年或者87年—— John Tukey 一直在讨论的问题就是，“怎样在线性回归中做变量变换，取得更好的预测效果？你应该用 log *X*还是用 *X*? 诸如此类”


有一阵子 Jerry 和我都在推敲这个问题。然后用光滑方法这个想法忽然在我脑海出现。我越想越激动。现在我还保留着其中一台旧苹果电脑，第一代有64kb内存的桌面电脑。它有一个彩色屏幕可以让你编程。所以我打电话给 Jerry，我说：“Jerry，快来，我在苹果上写代码，我们来看看它会不会有效。”


然后我们输入 *Y* 等于 *A* log *X* 加 *B* 这样的模拟数据，在 Apple 上跑了一个 ACE 的早期版本。每次在苹果的屏幕上输出一次迭代结果的时候，我们可以看到转换的迹(trace)


那台苹果电脑很慢，看到一个迹之后，Jerry 和我就去喝杯啤酒，然后再回来看下一次迭代得到的迹。到了半夜，终于可以判断，这该死的东西收敛到 *X* 的对数。我就知道我们成功了。之后我们需要做的事情就是写下来，加上理论和更多的实验。


我们把这个技术命名为 ACE 的故事是这样的：Jerry和我有天在 Shattuck Avenue 酒吧喝酒，讨论该起个怎样的名字。Jerry 坚持叫 ACE, 因为这个名字很帅，而且它是交叉条件期望(alternating conditional expectations)的缩写。我不太愿意。我说：“Jerry，这有点过了。我们怎能叫它 ACE 呢？”

然后忽然，Jerry 指着街对面。那里有一个 "ACE"。 他说：“看那个。”好像那是天堂之门。当然，我们当时看到的是 Ace 硬件商店的招牌。看到这让我相信 Jerry 是对的。它应该叫 ACE (Breiman and Friedman, 1985).

**Olshen**: 好，命名 PIMPLE (Breiman, 1991) 也像这样有故事吗？


**Breiman**: 不。PIMPLE 不太像这样。我——


**Olshen**: 先告诉我一点关于 PIMPLE 的事情。



**Breiman**: 好的。我当时对泛涵逼近很感兴趣，因为你可以把很多多元回归看作加了噪声的泛涵逼近。所以我读了很多高维泛涵逼近的文献。

我看到给方法，用单变量函数来逼近函数。就是说，如果你有一个核函数 $K(x, y)$， 你用 $F_i(x)$ 乘以 $G_i(y)$ 的积来逼近它。我仿佛醍醐灌顶，我想：“为什么不试试将函数展开成简单函数乘积这种办法来做回归的逼近呢？”


好。乘积符号是 pi(译者注：$\Pi$), 所以这是 pi 的来历。然后 pi 之后的单词是 "implementation"（实现）好了，自然而然的同义词是啥？PIMPLE!

**Olshen**:那 arcing, bagging 和 boosting 这些算法呢？


**Breiman**: 好的。耶，这些算法很迷人，Richard。在过去5年，预测方面有突破性的进展。而我认为，混合预测器就是两个大突破之一。这个想法就是，好，我们假设你用 CART, 它是一个相当好的分类器，但还不够好。我的意思是，在某些情况下，神经网络好得多。


**Olshen**: 嗯，在适当训练的情况下？


**Breiman**: 适当训练。


**Olshen**: 跟一个没有训练的 CART 相比？


**Breiman**:对。就是这样。我想我当时一直再考虑这个。我写了一篇关于线性回归中的变量子集选取的文章。我意识到线性回归中的子集选取问题非常不稳定。如果你稍微扰动一下数据，回归的5个最好的变量就会变成另外的五个。所以我想：“好。我们可以通过给数据加扰动把它稳定下来，得到五个最好的预测变量。然后再次扰动数据。再拿到五个最好的变换，最后把这些五变量的预测器作一个平均。”这确实做得很漂亮。这个结果在 Annals (Breiman, 1996b) 发表了。



接下来，CART 也有同样的特性。你知道的，如果你稍微改变数据，你会得到一棵非常不同的树。所以我就像，“那好，为什么我不试试在 CART 上做同样的事情呢？如果我改变数据生成一棵树，然后再次改变数据，生成另一棵树，最后取它们的均值或者让它们投票选出票数最多的类，没准我能提高准确性。”


所以问题变成怎样扰动数据？我那时候意识到，基于理论上的考量，最好就是从原始的数据集出发，从中自抽样，在自抽样样本中生成新的树，再取出另外的自抽样样本，在上面生成另外的树，如果是回归，我们就取它们的均值。如果是分类，就让它们投票选票数最多的类。

我把这种方法命名为 "bagging"，意思是“自抽样聚合”。它的预测精度不断提高，表现得非常漂亮。它还有很多令人激动的特性。之后 Yoav Freund 和 Robert Schapire (Freund and Schapire, 1996, 1997) 想出了一个算法，他们叫作 Adaboost。 Adaboost 采用了让训练误差下降尽可能快的方法将分类器组合在一起。它确实相当快。在大多数我见过的数据集里面，它用3到4个分类器就能把训练误差降低到0.


但很有趣的是，即使在训练误差下降到零之后，你继续往 Adaboost 算法里面组合更多的分类器，测试集的误差会在训练机误差为零之后长期保持下降。甚至在你组合了，比如说，一百个分类器之后，测试集误差还在下降。


你去看 Adaboost 的时候，你会发现，它用了一种比较复杂的方法，去增加那些在上一轮里面被误判的样本的权重。然后新的训练集就是根据这个权重，去取样，而不是像 bagging 那样等可能地抽样，之后把新的训练集给分类算法。这个算法效果好得不可思议。

在人们见过的大部分数据集里面，Adaboost 比 bagging 好很多。这是一个惊人的发现，简直就是化腐朽为神奇。就是，你用一个分类器，比方说一个常见的 CART, 它是一个好的分类，但又不是特别好，，但是用了 Adaboost 算法之后，这个编程很简单，只需要迭代调用 CART，它就变成一个世界级的分类算法，


所以问题变成：为什么这个复杂的算法做得这么好？


**Olshen**: 好得，让我们回头看看。我们现在讨论 boosting ?


**Breiman**: 对。 Adaboost. 当人们说起 boosting 的时候，通常就是讨论 Adaboost. 这是一个美妙，有点奇怪同时我们对它的了解还不是十分透彻的算法。


**Olshen**: 那 acing (Breiman, 1998) 呢？


**Breiman**: arcing 是这样来的。我第一次思考 Adaboost 并仔细观察它的时候，它的思路变得很清楚。你增加那些难以分类的样本的权重，这些观察样本更靠近分类的边界。


所以你仔细思索这个方法，就会有一整套的算法可以做同样的事情。你可以写下很多算法，这些算法会增加可能被错误分类的样本的权重，它会干得很好。我把这些方法叫作 acing, 意思是自适应重抽样或者自适应重定权重还有组合。所以，比如说，我给出一个特定的 arcing 算法可以和 Adaboosting 做得一样好。

意外地，组合方法，boosting 和 bagging，都没有考虑用树去做。几乎所有分类器都可以用树去做。这些方法是组合分类器或者回归的一般套路。有一篇关于分类器的好文章，他们仅仅用了简单超平面，随机超平面(Ji and Ma, 1997)。他们用 arcing 算法将随机超平面组合起来，取得了惊人的结果。

整件事情变得越来越有趣了。

###普查

**Olshen**: 您普查调整的工作继续了大数据集的研究，但是又和我们之前讨论的大不相同，您能谈一谈这方面的工作吗？

**Breiman**：我想想，在大约1987或1988年的时候吧，有一天David Freedman   突然给我说：“走，咱们一起去吃午饭吧。”

当我们一起吃午饭的时候，他说：你觉得让你待在提供的1990年的普查计划的委员会怎么样?


我说:“不,我还不想那样。但我会告诉你我想干什么。我之后会加入的,但是我不想在那里久待。”于是当时他让Ken watcher 加入了委员会。


Ken做的很好。在1989年末开始准备1990年的普查时，Dave给我打了个电话,说的话差不多是:"好吧.普查就好像是我自己的血肉一样,我希望你加入这次普查。"所以我对他说:"好"。

而且Dave和我开始前往各种各样为了2000年普查而建立的普查办公室。事实上他真的和一些户口调查员一起,去街上来视察普查是如何实施的。结束之后,大家分成了两拨人。


一拨是直接负责计数的人而另一种是调整普查而的人.错过普查的人数估计大约为总人口的2%,大概是五百万人.调整的方法主要是基于捕获再捕获的想法.我能对此做一个简短的介绍吗?好.



这是一个很简单的想法.假设你想知道一个湖里有多少条鱼。所以你去到那开始一直钓鱼,每次你钓上来一条鱼,你都会在它的背上作一个红色标记。



你最终完成并数了一下所有标记的鱼,一共10000条。你推测你自己已经数完了所有的鱼,但并不太确定。所以你接下来要做的事情是一周后回到这个湖边,然后抓100条鱼,看一看它们之中有多少是背上有记号的。现在一切顺利。


所以现在你抓了一百条鱼并且看一看它们之中有多少背上有标记.如果刚开始你抓到的的确是湖里面所有的鱼,那现在这100条里的每一条背上应该都有标记.但是你看着它们,发现只有98条在背上有记号.所以你就会发现自己第一次钓的时候，有2%的鱼没上钩过。（2%这个数为少算比率）



池塘中一共有超过10000条鱼。我事实上低估了2%.。是这里面有一个大问题:有些人发现这两条在背上没有标记的鱼。可能它们其中的一条在背上原本有标记,但是被擦掉了。所以这个比率不再是2%，而是下降到了1%。



可能还有些人仔细检查了另一条鱼,并且发现可能这条鱼背上也有个标记,这种情况下100条鱼中全是标记的鱼，说明你第一次钓鱼进行估计时没有少算。所以，你必须要知道100条鱼中有多少条是背上有标记的，这样才能准确地估计少算量。


现在,为了估计在1990年普查时的少算量,他们先做了普查,在普查之后他们又做了一个小样本的调查,我记得好像是50000户家庭吧,我记不太清具体的数字了。之后他们尝试通过匹配小型普查和原始普查的人,来观察两次调查的一致程度有多高。


举个例子,如果在小型调查中，有2%的人在原始普查中找不到,他们就会猜测普查的少算量为2%。同样,对于那些小型普查和原始普查没有匹配上的人，在了解了他们的特点和所在地的情况之后，调查员们也就可以知道错过普查的人都具有什么特点，以及这些人所在地的情况如何。


所以现在的问题是，这种调整的精确度有多高?这变成了一个很重要的法律案件,因为众议院里各州的议员席位数量是根据普查的人口数量来分配的,所以很多州都希望进行普查调整，他们都感觉自己州被少算了。


因此，普查调整意味着一小部分议会的席位可能由一州转向另外一州。此外,从联邦政府流向各个城市和各州数以亿计的钱，也是基于人口普查的数据。所以，究竟是采取原始的普查数据还是调整后的普查数据，这个问题是一个政治和经济的大问题。


所以我说:"好,Dave.这就是我要做的事情。"普查局已经用上千页的文档，来讲述大量的调整估计法，我会一页一页的仔细查看那些方法，并且看看这个调整进程的准确性。"


我在工业行业得到的经验是,如果你有一个数据集,你首先要做的事情是，尝试去确定目前你了解的数据质量好不好，有多少是缺失的，有多少是错误的等等。这时当你经历过挫折之后，才能学到的经验。然后我开始了审查,结果让我十分惊讶。

检查过程中，我发现很多所谓的调整，是由于明显的错误而导致的。我们要意识到:一方面，小型调查中你获得了100个美国人的100份资料；另一方面，你又拿了在原始普查中的100份资料,但问题是他们之中的多少是能匹配上的?


好吧,很多时候人们在普查时给的是不同的名。他们提供了不同的年龄,性别,你没办法将它们对应的那么好。你需要匹配了99%的人,才能有50%概率确定少算量就是2%。但是由于美国人的移动性,移民的社会地位等等因素的影响，匹配精度根本不可能达到99%。


如果你查看并且评估的话,错误越来越多的.正如你知道的那样,我最终在Statistical Sciene (Breiman,1994)写了一大篇文章,归纳了所有我之前基于普查文档所做的研究,并且很容易得出结论：普查调整出现的错误有80%是由于有不良数据,而且主要是在匹配时的错误。


现在,问题来了。,Richard.普查委员会承认，它内部的出版物中至少57%的有关1990年调整，都是由于不良数据。你会认为在被1990年的数据的评估打击如此之狠之后,他们应该不会再这么做了。因为如果有些环节失败了,你就不能再去重复了。好吧,他们在2000年所做的事情更有意思。他们竟然重做了一遍,但是连评估都没有!


###建议

**Olshen**:Leo,你在统计学,统计电脑处理、概率和教学这些方面有广泛的兴趣和贡献，你想对那些现如今想继承你的传统事业的年轻人提什么建议呢?他们应该学些什么以及为什么?


**Breiman**:好吧Richard,在某种程度上,我感觉我好像分裂了一样,因为我可能会告诉他们:"不要去学统计."我感觉在一定程度上,统计的学术方向可能已经迷失了.当我离开咨询顾问的职位，回到Berkeley Department时，,我感觉我好像如同爱丽丝梦游仙境一样.那感觉就是,我从统计应用的角度知道了工业机构和政府在发生些什么,但是学术研究正在进行的似乎离我们无比遥远.好像只是抽象数学的某一分支一样。前阵子我们这一学科的一位老前辈说:"我们需要保持Wald的精神不朽."但是在Wald时期以及统计从数据中分离出来之前，还是Fisher的鼎盛时期，Fisher相信统计的存在是为了预测、解释和处理数据的。(译者注:Fisher认为统计是为了预测、解释、处理数据；但Wald在此基础上将根据数据进行决策加入到了统计的范围内。)


在你今天早晨来之前,我翻出来了Webster词典并且找到了统计的定义,它是这么说的:"统计，收集、处理和分析事实或数据，并展示某种事物的主要信息。"如果使用单动词来描述它，就是"一门收集,分类,处理并且分析事实和数据的科学。"



现在,如今统计的学术圈里都没有那个定义了。举个例子,我正在看统计编年史,二十页历史里有一页有数据或者应用了数据处理的办法.这个比率并不比美国统计协会的日志里的高很多。所以我的观点是统计这个学科迷人的地方和通常的学术观点已经分道扬镳了。


在过去的五六年里,我与机器学习和神经网络区域的人走的很近,因为他们正在为一些庞大的困难的预测问题做一些非常重要的应用工作。他们以数据为方向,而且他们所做的正是与Webster 对统计的定义相一致.但是他们几乎全都不是受过训练的统计学家。


所以我认为如果我现在要给年轻人提建议的话,对于学统计，我持保留意见。,但是最后,我有可能会说:"去学统计吧,但是记住统计的美妙之处，是在收集和利用数据来解决现实世界中有趣而又重要的问题。"


###艺术家


**Olshen**:谢谢！从我们今天谈话的房间，甚至是整个房子的风格可以看出，你的兴趣爱好范围之广。你能谈谈作为艺术家的你是什么样子的吗？


**Breiman**:好吧.事实上，当我在洛杉矶当调查员的时候,，我可以在相当短的几个小时内赚到足够的钱，所以我有大把的空闲时间。而且我记得我遇到的第一个室友Cal，他是主修艺术的，我很喜欢他.他鼓励我去雕刻，而且我也做出了一些东西，,我当时并没有想太多。

之后我在洛杉矶有这段空闲时光时,我在UCLA分局报了一个雕刻班。那有一个很棒的老师鼓励我去做各种各样疯狂的事情。我也认识了一个曾经和我谈过一次的人——Alf Peterson，他
在威尼斯有一家铸铜的铸造厂。Alf是一个了不起的人，他说：“如果你想练习的话，就来我的铸造厂吧。我会展示给你看如何做这些事情。”


我用粘土，蜡和风屏做了一个人物。就在那，在那个角落，就是我的第一个“天使”（指向雕塑）。而且我拿着它去到了Alf的铸造厂，他说：“好，我将给您展示如何铸铜。”

他展示给我如何制作那个“天使”的模子，如何制作底盘，如何把它们放到烤炉中，如何注入铜等等。我十分好奇并且被深深地吸引了。我认为这是极好的，所以我从那时起就保持了这个习惯，而且我仍然很爱它。

然而，最近我开始用石头雕刻，这更有意思。所以你会发现石头做的头到处都是。这是一项漫长的工作，你需要坚持用锤子和凿子不断敲打。


**Olshen**:我觉得我的问题已经问完了.我马上要离开了，你有什么简短的想法吗?刚才的采访是否有趣呢?


**Breiman**:这的确非常有趣,Richard。你知道,有时候我对统计感到很伤心。现在有太多聪慧的人加入到这个行业,我希望在人太多而导致变差之前，统计能变得更好。


**Olshen**:或许你自己的例子会给别人带来正面积极的影响。谢谢你。

**Breiman**：Richard，这是我的荣幸。

