---
title: "Breiman Page 6-10"
output: html_document
---

### SANTA MONICA, MEXICO, THE SCHOOL BOARD AND TEACHING KIDS MATHEMATICS
**Olshen**: That’s just fine. Now, somehow all of this or a lot of it seems to have taken place in Santa Monica. I’m curious about your other involvements in Santa Monica, for example, with the Santa Monica School Board, how you came to be not only on it, but also its leader.

**Olshen**: 很好。现在看来，这些工作全部或者说很大一部分都是在 Santa Monica 进行的。我对你在 Santa Monica 进行的其他工作很好奇，比如说，Santa Monica 校董会，你是怎么参与其中的工作，还成为它的领导者的？

**Breiman**: Well, let me back up a little bit on that one. My friends and I got to know this little village about 30 miles north of Puerto Vallarta called Mezcales. At the time, I was taking care of two or three kids even though I was a bachelor. But they were kids of friends of mine who had gone to Saudi Arabia to work and decided that was not a good place for kids to be.

So they sort of turned them over to me. And one of the kids was a young boy who was getting picked on by two older girls. I wanted to find another boy to even the score, but I couldn’t find another boy whose parents were willing to let go of him. Then somebody asked why not take up a couple of young Mexican boys from this village of Mezcales.

I went through an incredible hell with the bureaucracies—both Mexican and the United
States—but I managed to get these two kids up to live in my house with me. At that time it was in Topanga Canyon. They went to the local grammar school along with my American kids, and it was a great success.

---
title:"Breiman Page 11-15"
output:html_document
---

### SENSUS
**Olshen**: Continuing in the spirit of large data sets, but very different from what we’ve discussed thus far, can you talk about your involvement in work on the Census adjustment?

**Olshen**: 您能谈一谈您在既要保持大数据的设定又要和我们之前讨论的有所不同的情况下的有关普查的调整的进展吗?

**Breiman**: As I recall, in about 1987 or ’88, David Freedman said to me rather unexpectedly one day, “Come on. Let’s go have lunch together.”

**Breiman**：据我回忆，在大约1987或1988年的时候吧，有一天David Freedman突然给我说：“走，咱们一起去吃午饭吧。”

As we were having lunch together, he said, “How would you like to be on this committee that’s looking over plans for the 1990 Census?”

当我们一起吃午饭的时候，他说：你觉得让你待在提供的1990年的普查计划的委员会怎么样?

And I said, “No. I don’t want that. But I’ll tell you what I’ll do. I will get involved later on. But I don’t want to sit in on this committee.” And then he got Ken Wachter to sit in on the committee.

我说:“不,我还不想那样。但我会告诉你我会做的。我之后会加入的,但是我不想在那里久待。”于是当时他让Ken watcher 加入了委员会。

Ken did a wonderful job. Now, as the beginning of the 1990 Census rolled around in 1989, Dave called me up and said, more or less, “Okay. I’m claiming my pound of flesh. I want you to get involved in the Census.” So I said, “Okay.”

Ken做的很好。在1989年末开始准备1990年的普查时，Dave给我打了个电话,或多或少的对我说:"好吧.普查就像是我自己的肉一样,我希望你加入这次普查。"所以我对他说:"好"。

And Dave and I began taking trips to various Cen-sus of offices as they became set up for the year 2000. He actually walked the streets with some of them [the census takers] to see how it was being done. And then it was over and that Census produced two different sets of figures.

而且Dave和我开始前往为了2000年普查而建立的各种各样的普查办公室。事实上他真的和一些户口调查员一起去街上来视察普查是如何实施的。这种观察之后就结束了,并产生了两种不同类型的人。

One was just a straight enumerative count and the other was an effort to adjust the Census. The people that the Census missed were estimated to be about 2% of the population, or five million people. The way that the adjustment was made was basi-cally in terms of the capture–recapture idea. Shall I give a brief description of this? Okay.

一种只是直接负责计数的人而另一种是为调整普查而付出精力的人.普查错过的人数估计大约为总人口的2%,或者说五百万人.调整的方法主要是基于征收-再征收的想法.我能对此做一个简短的介绍吗?好.

It’s a simple idea. Suppose you want to know how many fish are in a lake. All right. So you go there and you fish and you fish and you fish, and each time you pull out a fish, you put a red mark on its back.

这是一个很简单的想法.假设你想知道一个湖里面有多少条鱼。好,所以你去到那开始一直钓鱼,而且每次你钓上来条鱼,你都会在它的背上作一个红色标记。

You finally finish and you’ve counted, say, 10,000 fish. And you figure that you think you’ve got them all, but you’re not sure. So what you’re going to do is a come back a week later and you say, “Okay. Now I am going to catch a 100 ???sh and see how many of them have got marks on the back.” All right.

你最终完成并数了一下,说,10000条鱼。而且你认为你已经钓到全部的鱼了,但你并不确定。所以你接下来要做的事情是一周后回到这个湖边,然后你说:"好.现在我打算抓100条鱼然后看一看它们之中有多少在背上有记号。"现在一切顺利。

So you catch 100 fish and see how many have got marks on the back. Now, if originally you had captured all the fish in the lake, every one of those 100 would have a mark on its back. But you look at them, and only 98 have marks on the back. So you say, “Oh, I didn’t get 2% of them the first time around.”

所以现在你抓了一百条鱼并且看一看它们之中有多少背上有标记.如果刚开始你抓到的的确是湖里面的所有鱼,那现在这100条里的每一条背上应该都有标记.但是你看着它们,发现只有98条在背上有记号.所以你说:"哦,我第一次钓的时候有2%的鱼没钓上来过。"

There are more than 10,000 fish in the pond. I actually underestimated by 2%. But here is the big problem: Somebody notices that of the two fish that didn’t have marks on their backs, maybe one of them had a mark on its back, but it got rubbed off. So the undercount is no longer 2%. It’s gone down to 1%.

池塘中一共有超过10000条鱼。我事实上低估了2%.。是这里面有一个大问题:有些人发现这两条在背上没有标记的鱼。可能它们其中的一条在背上原本有标记,但是它被擦掉了。所以少计算的不超过2%.比率降到了1%。

Maybe somebody else examines the other fish very carefully and notices that there may have been a mark on that fish’s back, too, in which case there’s no undercount. So notice then that you have to be able to match these fish to within 1 in 100 to get an accurate estimate of the undercount.

可能别的人仔细检查了另一条鱼并且发现可能这条鱼背上也有个标记,这种情况下就没有少算的了。所以注意现在你可以通过这些100条里抓上来1条的鱼来对少算的量进行一个准确的估计。

Now, to estimate the undercount in the 1990 Census—they did the Census first. Then they followed it by a mini-Census consisting, I think, of something like 50,000 households, I’m not sure of the exact number. Then they tried to match the people in the mini-Census to the original Census to see what kind of agreement they got.

现在,为了估计在1990年普查时的少算量,他们先做了普查,在普查之后他们又做了一个小样本的调查,我记得好像是50000户家庭吧,我记不太清具体的数字了。之后他们尝试去通过匹配小型普查中的人和原始的普查数据来看一看两次调查能达到多高程度的一致。

And, for instance, if 2% of the people in the mini-Census were not found in the main Census, they would just assume that the main Census had under-counted by 2%. Also, by knowing the characteristics and location of the people in the mini-Census that weren’t found by the main Census, they would know the characteristics and location of the people the Census had missed.

举个例子,如果在小型调查中的人有2%并没有在主要的普查中找到,他们应该需要假设普查的少算量为2%。同样,在知道了没有在普查中找到的那些小型调查中的人的特性和所在地的情况下,他们也可以知道普查错过了的人的特性和所在地。

Now, so the question was how accurate was this adjustment? This became a big court case because many states wanted an adjustment. They felt they had been undercounted, and Congressmen in the House of Representatives are apportioned on the basis of Census population.

所以现在的问题是这种调整能达到多精确?这变成了一个很大的法律案件,因为众议院里各州的议员席位是基于普查的人口来分配的,所以很多州都希望能够有调整.他们都感觉自己州被少算了。

So adjustment could mean that a few congressional seats might swing from one state to another. Plus, a lot of the billions of dollars of federal money that goes out to cities and states are based on Census figures, so which set of figures to adopt -the original or the adjusted —was a very political, big money question.

所以调整意味着一小部分议会的席位可能由一州转向另外一州。此外,联邦政府数以亿计的流向城市和各州的钱是基于普查的人数,所以确定人数的方法,无论是最初期的还是调整过的,都是一个政治和经济的大问题。

So I said, “Okay, Dave. Here is what I’m going to do.” The Census Bureau had done a large evaluation of the adjustment with thousands of pages of documentation. And I said, “I’m going to look carefully at this evaluation and go through it page by page and see what it says about the accuracy of this adjustment procedure.”

所以我说:"好,Dave.这就是我要做的事情。"普查局已经写了上千页的文档,做了大量有关调整的估计评价,所以我说"我会一页一页的仔细查看那些评价并且看看他写的关于这个调整进程的准确性。"

My experience in industry had been, if you get a data set, the first thing you do is you try to find out how good the data is you know, how much is missing, how much is in error and so on. That’s one thing you really learn by hard-knocks experience. And I began going through, and I was amazed.

我在工业得到的经验是,如果你有一个数据集,你首先要做的事情是尝试去确定你了解的数据多少是有价值的,多少是缺失的,多少是错误的等等.那是一件你经历过挫折才能学到的事情。然后我开始了审查,结果让我十分惊讶。

More and more of this supposed adjustment was clearly due to errors than anything else. Realize this: Here on one hand you’ve got, say, 100 slips of paper about 100 Americans from the mini-Census; on the other hand, you’ve got 100 slips of paper from the main Census, and the question is how many of them can you match?

相比其他的事情,多得多的这种应有的调整很明显是由于错误而导致的。我们要意识到:在你收获的一方面,你说的是从小型调查中得到的关于100个美国人的100份资料;而在另一方面,你又拿了在普查中的100份资料,但问题是他们之中的多少你能对应上?

Well, many times people give different, say, middle names to the Census. They give different ages, different sexes. You can’t match people that well. You need 99% accuracy in matching to get 50% accu-racy in a 2% undercount. So the whole problem is that Americans, because of their mobility and immigrant status and so on, cannot be matched to within 99%.

好吧,很多时候人们在普查时给的是不同的名。他们提供了不同的年龄,性别,你没办法将它们对应的那么好。你需要99%的准确性才能在2%的少算量的情况下有50%的精确度。由于美国人的移动性,移民的社会地位等等因素的影响,所以整个的问题是美国人不可能做到能够匹配对应达到99%。

And so if you look at it and evaluate, the errors pile up. As you know, I finally wrote a big paper in Statistical Science (Breiman, 1994), summarizing all the research I had done based on Census docu-ments, and I concluded that easily over 80% of the estimated Census adjustment was due to bad data, mainly errors in matching.

而且如果你查看并且评估的话,错误是逐渐积累的.正如你知道的那样,我最终在StatisticalSciene(Breiman,1994)写了一大篇文章,归纳了所有我之前基于普查文档所做的研究,并且最终简单的得出结论:超过80%的估计的普查调整是由于不良数据,而且主要是在对应时的错误。

Now, here is the thing that floors me, Richard. The Census Bureau admits in its own internal publications that at least 57% of its proposed 1990 adjustment was due to bad data. You’d think that after getting stung so badly by the data and the evaluation of the adjustment in 1990, they wouldn’t try to do it again. Because if something fails, you just don’t repeat it. Well, what they’re doing instead in 2000 is most interesting. They’re going to do it again, but not evaluate it!

现在,有问题难倒我了,Richard.普查委员会承认它内部的出版物中至少57%的有关1990年调整的都是由于不良数据。你会认为在被1990年的数据的评估打击如此之狠之后,他们应该不会再这么做了。因为如果有些环节失败了,你就不能再去重复了。好吧,他们在2000年所做的事情更有意思。他们竟然重做了一遍,但是连评估都没有!

###ADVICE
**Olshen**: Leo, you have a record of wide ranging interest in and contributions to statistics and statistical computing and probability and pedagogy. What advice would you give to a young person today who wants to continue in your traditions? What should he or she study and why?

**Olshen**:Leo,你在统计学,统计电脑处理、概率和教学这些方面有广泛的兴趣和贡献，你想对那些现如今想继承你的传统事业的年轻人提什么建议呢?他们应该学些什么以及为什么?

**Breiman**: Well Richard, I’m torn in a way because what I might even tell them is, “Don’t go into statistics.” My feeling is, to some extent, that academic statistics may have lost its way. When I came, after consulting, back to the Berke-ley Department, I felt like I was almost enteringAlice in Wonderland. That is, I knew what was going on out in industry and government in terms of uses of statistics, but what was going on in academic research seemed light years away. It was proceeding as though it were some branch of abstract mathematics. One of our senior faculty members said a while back, “We have to keep alive the spirit of Wald.” But before the good old days of Wald and the divorce of statistics from data, there were the good old days of Fisher, who believed that statistics existed for the purposes of prediction and explanation and working with data.

**Breiman**:好吧Richard,在某种程度上,我感觉我好像分裂了一样,因为我可能会告诉他们:"不要去学统计."我感觉在一定程度上,统计的学术方向可能已经迷失了.当我在咨询过,回到了Berkeley Department之后来到这里的时候,我感觉我好像如同爱丽丝梦游仙境一样.那感觉就是,我知道从统计应用的角度工业机构和政府在发生些什么,但是学术研究正在进行的似乎离我们无比遥远.好像只是抽象数学的某一分支一样。前阵子我们这一学科的一位老前辈说:"我们需要保持Wald的精神不朽."但是在Wald的时期以及统计从数据中分离出来之前,还是相信统计的存在是为了预测和解释以及处理数据的Fisher的鼎盛时期。

Before you came this morning, I pulled out Webster’s dictionary and looked for the definition of statistics, and here is how it goes: “Statistics, facts or data of the numerical kind assembled, classified, and tabulated so as to present significant information about a given subject.” When used with a singular verb, it is, quote, “The science of the assembling, classifying, tabulating, and analyzing such facts or data.”
 
在你今天早晨来之前,我翻出来了Webster词典并且找到了统计的定义,它是这么说的:"统计,可用数字收集的,分类的,处理的为了展现给定事物特定信息的事实或者数据。"如果使用的是单一的动词时,它写的是"一门收集,分类,处理并且分析事实和数据的科学。"

Now, little of that is going on in the academic world of statistics. For instance, I was looking at The Annals of Statistics and I estimate that maybe 1 paper in 20 had any data in it or applied the methods there to any kind of data. The ratio is not much higher in the Journal of the American Statistical Association. So my view of what’s fascinating in the subject of statistics and the common academic view are pretty far apart.

现在,那个定义里的内容几乎都没有在如今统计的学术世界里。举个例子,我正在看统计编年史,我估计大约二十页历史里有一页有数据或者应用了对任意数据处理的办法.这个比率并不比美国统计协会的日志里的高很多。所以我的观点是统计这个学科迷人的地方和通常的学术观点已经分道扬镳了。

In the past five or six years, I’ve become close to the people in the machine learning and neural nets areas because they are doing important applied work on big, tough prediction problems. They’re data oriented and what they are doing corresponds exactly to Webster’s definition of statistics, but almost none of them are statisticians by training.

在过去的五六年里,我与机器学习和神经网络区域的人走的很近,因为他们正在为一些庞大的困难的预测问题做一些非常重要的应用工作。他们以数据为方向,而且他们所做的正是与Webster 对统计的定义相一致.但是他们几乎全都不是受过训练的统计学家。

So I think if I were advising a young person today, I would have some reservations about advising him or her to go into statistics, but probably, in the end, I would say, “Take statistics, but remember that the great adventure of statistics is in gathering and using data to solve interesting and important real world problems.”

所以我认为如果我现在要给年轻人提建议的话,我会对于建议他们去学统计有所保留,但是最后,我有可能会说:"去学统计吧,但是记住统计的美妙旅程是在收集和利用数据来解决现实世界中有趣而又重要的问题中。"

###The artist
**Olshen**:Thank you. The room in which we are having this conversation, even the house itself, is full of reminders of the breadth of your interests, not least your life as an artist. What about that side of Leo Breiman?

**Olshen**:谢谢.我们在进行对话的这个房间,甚至这件房子,全都充分地告诉我你的兴趣爱好范围之广,尤其是你作为艺术家的生活。这方面的你是什么样子的?

**Breiman**: Well, during my consultant time in Los Angeles, I could actually make enough money in a fairly small number of hours that I had a fair amount of leisure time. And I remembered that when I first came up to Cal, my first roommate, of whom I was very fond, was an art major. He encouraged me to sculpt and I made some things out of clay. I didn’t think much of them.

**Breiman**:好吧.当我在洛杉矶当调查员的时候,我事实上可以在相当短的几个小时内赚到足够的钱所以我有大把的空闲时间。而且我记得我遇到的第一个室友Cal,是主修艺术的,我很喜欢他.他鼓励我去雕刻而且我也做出了一些东西,我当时并没有想太多。

Then when I had this leisure time in Los Ange-les much later on, I took a sculpting class at UCLA Extension. There was a wonderful teacher who encouraged us to do all sorts of wild things. I also met this fellow, who came and talked to us once, who had a foundry for bronze casting in Venice—Alf Peterson. Alf was a marvelous guy And he said, “If you want to practice, come down to the foundry. I’ll show you how to do things.”

之后我在洛杉矶有这段空闲时光时,我在UCLA分局报了一个雕刻班。那有一个很棒的老师鼓励我去做各种各样疯狂的事情。我也认识了一个曾经和我谈过一次的人——Alf Peterson，他
在威尼斯有一家铸铜的铸造厂。Alf是一个了不起的人，他说：“如果你想练习的话，就来我的铸造厂吧。我会展示给你看如何做这些事情。”


I made a figure out of clay and wax and chicken screen. That was my first angel over there (indicating) in the corner. And I took it down to Alf’s place and he said, “Okay. I’m going to show you how to cast bronze.”

我用粘土，蜡和？？？做了一个人物。那，在那个角落，就是我的第一个“天使”（指向雕塑）。而且我拿着它去到了Alf的铸造厂，他说：“好，我将给您展示如何铸铜。”

He showed me how to make molds of the angel, how to make the negatives, how to put it in the ovens, how to pour the bronze and so on. I was intrigued and absorbed. I thought that it was terrific And so I’ve kept going ever since then and have loved it.

他展示给我如何制作那个“天使”的模子，如何制作底盘，如何把它们放到烤炉中，如何注入铜等等。我十分好奇并且被深深地吸引了。我认为这是极好的所以我从那时起就保持了这个习惯而且我仍然很爱它。

Lately, though, I’ve begun working in stone, which is very interesting. So you’ll see some stone heads also drifting around. And that’s slow work. You’ve got to keep tinkling, tinkling with the hammer and chisel.

然而，最近我开始用石头雕刻，这更有意思。所以你会发现石头做的头到处都是。这是一项漫长的工作，你需要坚持用锤子和凿子不断敲打。

**Olshen**: I guess I’m done with my questions. Have you any brief parting thoughts? Has this been fun?

**Olshen**:我觉得我的问题已经问完了.我马上要离开了，你有什么简短的想法吗?刚才的采访是否有趣呢?

**Breiman**: This has been a lot of fun, Richard. You know, sometimes I feel sad about statistics. There are so many smart people in it and I hope it gets better before it gets worse.

**Breiman**:这的确非常有趣,Richard。你知道,有时候我对统计感到很伤心。现在有太多聪慧的人加入到这个行业,我希望在人太多而导致变差之前统计能变得更好。

**Olshen**: Perhaps your own example will have a positive effect on others, Leo. Thank you.

**Olshen**:或许你自己的例子会给别人带来正面积极的影响。谢谢你。

**Breiman**: Richard, it’s been a pleasure.

**Breiman**：Richard，这是我的荣幸。
