---
title: "WANGJIA"
author: "WangJia"
date: "2016年12月21日"
output: html_document
---
##任何学科中都没有重要的研究可以回答这个问题“这句话是什么意思”

**DeGroot**: 让我们来谈谈概率吧。你说你不能接受主观概率的概念。你用什么定义概率？

**Stein**: 基本上是柯尔莫哥洛夫的。这是一个数学系统。
	
**DeGroot**: 任何一组满足概率演算公理的数字。

**Stein**: 是的。

**DeGroot**: 但是这些数字在现实世界中代表什么呢？

**Stein **: 好吧，其实并没有唯一的解释。当然我说的是柯尔莫哥洛夫对概率旧的解释，而不是复杂的解释。在他的书中他简要的提到两方面的解释。其一是传统的长时间内事件发生的相关频率。其二是，当人们提出一个概率模型，这个模型被用到严格地解释现实世界的现象时，人们会断言任何小概率的单一特定时间在原则上时不会发生的。这结合了强或者弱的大数定律，是比频率概念更加宽泛的解释。事实上，频率解释在某些意义上是多余的。这并没有回答“当我说下次骰子掷到6点的概率是1/6，这种状况意味着什么”。在任何学科中都没有研究可以回答这个问题“这句话是什么意思”。正是这个错误的哲学观点导致了这类问题。

**DeGroot**: 你觉得概率只能应用到像骰子掷到6这样的事件吗?

**Stein**: 不不。我们对任何事情都可以建立概率模型。

**DeGroot**: 即使他们是不可重复的？

**Stein**: 是的。

**DeGroot**: 但是如果你只能解释很小或者很大的概率，你怎样在一次性情况中分配中等大小的概率？

**Stein**: 对于任何现象而言，建立数学模型都是历史进程的结果，建立概率模型也是如此。在科学研究的可接受性和严肃性方面，概率模型往往落在后面。他们比物理模型更随意更简单。但这并不会令概率模型完全不适合作为模型。概率模型唯一性的缺失同样困扰着人们。例如，一个人可能针对某一现象提出两个可替代概率模型，一个贝叶斯学派的人面对这种情况，会直接使用这两个模型计算概率，用那种方法将概率混合。如果一个人根据经验来判断，他无法在世界单一实现的基础上来区分这些混合物。即使后来人们发现两个模型之一是正确的，也无法证明他是完全正确的，而不是半对半两个模型的混合。所以人们会发现这种困扰，【但这只是】。概率模型没有和其他物理模型一样的唯一性。

**DeGroot**: 那意味着在模型的建立和数值概率中主观因素无可避免。

**Stein**: 那不同于“有任何事情是未知的情况下，绝不允许考虑概率模型”这种说法，那是贝叶斯观点最严格的解释。一些统计学家尝试接受这种观点作为哲学立场的一部分，但是在实践却否认它，这是很不合理的。

##“或许我并没有一名真正统计学家应具有的特质”

**DeGroot**: 在你当空军的日子里，有遇到应用的问题吗？

**Stein**: 并没有。很遗憾，我没有做重要的应用研究。很难想起我所做过的任何应用研究。我认为这主要有两个原因。其一是人们更倾向于被要求做他们擅长的事。正如我所说，我很懒，我没有时间做我需要做的事和应用统计。这真令人遗憾。另一个事实是，做出真切的统计分析并让人们接受它，我做不出这种程度的应用统计工作，因为我没有足够的自信。或许我并没有一名真正统计学家应有的特质。

**DeGroot**: 可能部分的犹豫是对统计模型作为恰当工具缺乏信任？

**Stein**: 不是的。一些人可能有这种普遍怀疑主义，但是我并没有。[笑]很显然概率和统计模型是非常有用的，在大多数情况下是处理自然现象重要且正确的方式。有各种各样的原因导致我没能够做。现在我能做的就是在文献中从事数据分析。我的个性不会造成干扰，但时间确实是个大问题。现实问题都是极其复杂的，这种复杂性导致你无法给出符合理论的处理方式。有人必须来解决这个问题。当然，在计算机的帮助下，人们现在能够计算很多东西。我认为应该有更多理论与实践的结合。很遗憾我已经上了年纪没能来做这个。

**DeGroot**: 你认为统计研究领域中应用统计和理论统计有合并的趋势吗？

**Stein**: 没有。

**DeGroot**: 所以你认为统计中理论统计学家和应用统计学家仍然是相对【分隔/独立/割裂。。再想一想】的？

**Stein**: 是的，我认为是这样的，甚至是更加【分离】。现在有更多计算的可能性，并且它们很多都是非常有用的。人们可以通过某些任意计算方法去发现传统统计方法无法发现的事情。另一方面，他们也可能发现并非真实存在的事物。

**DeGroot**: 换句话说，你认为计算能力的发展加深了这种【分离】，因为人们可以仅仅用计算机就解决应用问题，而不需要有理论。

**Stein**: 是的

**DeGroot**: 你认为计算机是理论研究的工具吗？

**Stein**: 当然啦。我很遗憾自己没有学会怎样恰当的计算。我有一台小的IBM电脑，但是我只会用BASIC，我做任何事都是从头开始。我希望我能够非常确定自己知道正在做什么，所以我并不喜欢程序包。我的计算机上没有包，也从没有了解过怎样用更大的家伙。但我希望下个学季自己有更多时间的时候可以学一下。

**DeGroot**: 我听说你现在正在给一个大班教概率引论课，这个班有多少学生？

**Stein**: 大概有180人。我对自己的基础教学并不满意。我对教科书也不满意。有时我想自己来写一本书。但是写一本基础教材，除了以系统的、简单的、可理解的和正确的方式展示想法以外，还需要做很多事。除了基础文本以外还需要有很多内容，这也正是大部分教材不完善的地方。你需要给出练习题，需要给出解释，需要举例子。当然，这些组合到一起才能完整的展示想法。

**DeGroot**: 当你教课比如概率引论的时候，你有用新颖的方式来传授基础概念吗？

**Stein**: 并没有。我快受不了教课的过程了，教科书总是把人往错误的方向带。

##“不知怎么，我似乎不像其他人那样思考”

**DeGroot**: 当你不做统计的时候你喜欢干什么？跟我们分享一下统计之外你的生活、你的爱好或者其他的活动吧。

**Stein**: 我有妻子和三个已成年的孩子。在孩子们小的时候，他们占据了我大量的精力。越南战争期间，我积极参加反战活动，现在我有时仍然积极参加和平运动。但遗憾的是，我已经渐渐远离它，部分原因是我不适合任何类型和他人的互动。我参与运动仅仅是因为我认为自己应该去做，而不是因为我喜欢它。最近我有点更不务正业了，我进行了大量的徒步旅行。我每周会跑3次步，跑10英里，虽然跑得并不多，但是对我这个懒人来说已经很难得了。我参加了本地的一个徒步旅行团――“洛马???普雷塔的塞拉俱乐部”我们每周末都会组织徒步活动。

**DeGroot**: 你认为你的政治观点对你所研究的问题的类型和你的科学哲学有影响吗？还是说他们是独立的吗？

**Stein**: 我想说他们很大程度上是独立的。当然，我并不从事军事工作，即使是名义上。事实上，我已经有18年没有军事合同。但这是个很难回答的问题。我承认我的研究和我的政治态度在很大程度上是独立的。我并不认同Lindley的观点，即概率的主观方法是马克思主义者或社会主义者的产物。

**DeGroot**: 我注意到你的书架上除了统计类的书还有一些Dorothy Sayers和Edgar Allan Poe的书，这肯定不是你课程的教材，所以它们是你的课外读物吧？

**Stein**: 是用来放轻松的书。

**DeGroot**: 你一定很喜欢读推理小说。

**Stein**: 曾经有段时间很着迷，现在没那么着迷了。

**DeGroot**: 自从1953年你加入斯坦福统计系，你在西雅图、伯克利、康奈尔、牛津和欧洲其他多地休假……我很好奇休假时你会做些什么？当你离开的时候，你会改变你的工作风格或者研究的主题吗？

**Stein**: 并没有。有时我会受外界影响因素的影响，比如我身边的其他人或者仅仅是我最近读的一些文章。但是这些往往是相当次要的东西。最近就有两个。我在Turan-Kubilius上发表了一篇关于概率数理论的文章[Tech. Report No.220,Dept. of Statistics, Stanford Univ., July 1984]，那就是受匈牙利数学家Ruzsa的一篇文章的启发写出来的。然后，David Hinkley 在这的研讨课导致我做了一些基于先验分布对Welch和Peers置信集 [Welch, B. L. and Peers, H. W. “On formulae for confidence points based on integrals of weighted likelihoods” J. Roy. Statist. Soc. Ser. B 25(1963)318-329] 的研究。我写了一篇关于这个话题的技术报告。[Tech. Report No.180, Dept. of Statistics, Stanford Univ. November 1981; to appear in the Proceedings of the Banach Center, Warsaw] 它的想法就是选择合适的先验分布，可以得到不同于1/n名义概率覆盖的概率覆盖，几乎任何的先验分布会给出1/n1/2。在一维中，它是Jeffreys先验，在更高维中显然就不是了。

**DeGroot**: 我了解。我感觉你研究的大多数问题是以某种方式内部生成并且非常吸引你的有趣的问题。

**Stein**: 是的。大多数问题是内部生成的，如果是外部产生的问题，我研究他们的部分原因是我的思维方式导致有一些想法。但也有一些案例跟我其他的研究并不相关。

**DeGroot**: 你未来有什么打算吗？

**Stein**: 我不知道。我希望有更多的时间做自己的事。我快受不了教学和我所答应的那些讲座了，所以我想退休了。我也不确定，或许可以说是半退休。

**DeGroot**: 你指的是从现在起的六年？

**Stein**: 不，从现在起一年。或许有更多的时间去旅行，虽然对我来说那不是完成工作最好的方式。然而，事实上上次我离开的时候已经完成了相当多的工作。

**DeGroot**: 我想说这些年你已经完成了相当数量的研究。事实上，虽然你声称自己很懒，但你已经完成的大量研究却反驳了这一点。因为有的研究已经做完了，只是还没写出来而已。统计世界认可并感谢你所完成的研究。我也认为此次对话涵盖了相当数量认可与感谢你的理由。

**Stein**: 好吧。等我看到这次谈话的文字记录时我可能会对我的一些回答进行修正。不知怎么，我似乎不像其他人那样思考。不同的人有不同的想法是好的。

**DeGroot**: 非常感谢。
