---
title: "与Charles Stein的对话"
author: "zhangyet"
date: "2016/12/17"
output: html_document
---


## 摘要
Charles Stein于1920年3月22日出生在纽约布鲁克林，1940年在芝加哥大学获得数学学士学位。二战打断了他的研究生生涯，1942到1946年期间，他在美国空军服役，并以上尉军阶退役。1947年他在哥伦比亚大学获得数理统计博士学位，并成为加州大学伯克利分校统计实验的教员，他在那里待了两年[待推敲]。1949到1950年期间，他是巴黎亨利庞加莱学院的国家研究委员会成员，1951到1953年任芝加哥大学的统计副教授。1953年之后，他在斯坦福大学统计系任职，现在他已经是统计系教授。

以下对话于1984年10月在他的办公室中进行。[带推敲：整个摘要都翻译得太粗糙了]

## “我一直都想当数学家。”

**DeGroot**: 你是怎样产生对统计的兴趣最终进入统计领域的？

**Stein**: 嗯，大约是我在芝加哥大学念研究生的时候，我修了几门Walter Bartky的概率和统计课程。1940年毕业之后，我还没有找到工作的时候，我参加了精算师的头三门考试。我没有通过第三门关于概率和统计的考试，partly out of discouragement from thinking that I had done very badly on the first two. 然后当我回到芝加哥大学的时候，我选修了更多概率和统计的课程。

**DeGroot**: 你是作为研究生回去的？

**Stein**: 当了半年的数学研究生。

**DeGroot**: 这段时期持续了多久？你说过你失业了。

**Stein**: 我失业了一年，然后当了半年数学研究生。我要取得硕士学位，那时候我在写点东西充作硕士论文。那是关于von Mises的$\omega^2$ criterion在双样本情况下的分布的文章。我读了Smirnov的文章，几乎是逐行把它从单样本扩展成双样本。毫无创意的工作，幸好，它从来没有发表。(笑) 之后，Murry Rosenblatt 在恰当的假设下正确地完成了这个工作[带推敲]。那时已经是二战，我在空军服役，主要是在五角大楼司令部做气象学的工作。在那里我做了很多统计工作。我和Kenneth Arrow、Gil Hunt、George Forsyth、Murray Geisler以及其他几个相当不错的数学家一起工作，但不知怎的，我最后跟他们分道扬镳了。

**DeGroot**: 处理这些问题引起的兴趣将你引回统计研究所吗？

 **Stein**: 是的。当然我一直都想当数学家，但我发现如果我要在纯数学方面拿到学位，I would have had to accept guidance in my choice of topic; 然而，我已经发表了一篇关于Student假设在幂独立于方差的情况下双样本测试的文章了[Ann. Math. Statist. **16** (1945) 243-258]，这是我和Kenneth Arrow之间非正式谈话以及浏览Waid的一些工作的结果。

 **DeGroot**: 所以你想成为统计方面的博士生，并以这个成果作为你论文的基础？

 **Stein**: 是的，而且我做到了。1946年二月我被空军解雇之后我马上就去了哥伦比亚大学，一年半之后就拿到学位了。然后Neyman给了我一份在伯克利的工作，所以我铁了心搞统计了。

 **DeGroot**: 你在伯克利的时候，Wald在哥伦比亚吗？

 **Stein**: 是的， Wald在那里。Hotelling刚走，Wolfowitz也在那里。P. L. Hsu正在访问;Doob也是；B. O. Koopman在那里，在另一个系。Ted Anderson在下一年来了。

 **DeGrood**: 虽然你已经完成你的论文了，但是还是和他们联系起来来？[待推敲]

 **Stein**: 是的。

 **DeGroot**: 让我们回头一下。你在芝加哥读学士的时候你学了什么？那是Hutchins当校长的时候，有一个通识教育计划？那是你失业的原因吗？

 **Stein**: 不，还没有强制的通识教育。在头两年我们要求上四门普查课程加上英语还有一门外语以及一些数学课程。但除此之外，我们自由自在，想干什么就干什么。L. M. Graves教授给了我很大的鼓励。我在那里的第一学季我选了他当分析几何的老师。他鼓励我第二学季选修本科的分析课程。同时，我第二学季的微积分学得很糟糕，但他帮我向Sanger教授求情，让我可以在他那里上课。那门课程我上得很差劲但我的实分析很好。So that was the start of a very mixed career in mathematics. 第二年Saunders Mac Lane来访问，他上第一学季的代数课，这门课后来成为研究生入门课程，但它只是哔Brikhoff和Mac Lane的书稍微高级一点。第二第三学季的课是Albert上的，我相信是的，用他自己的《现代高等代数》(*Modern Higher Algebra*)

 **DeGroot**: 关于Birkhoff和Mac Lane你有什么想说的吗？[待推敲:Had you had any experience in the Birhoff and Mac Lane type of material?]

 **Stein**: 不。我不太懂代数，但其实你并不一定需要懂很多。这就是纯数学美妙的地方。它有一种自包含的趋势。

 ## “不经意我就研究起群论来”

 **DeGroot**: 一个纽约布鲁克林的男孩怎么就去了芝加哥大学了呢？

 **Stein**: 嗯，其实在我小时候我家就搬去皇后区了。

 **DeGroot**: [笑]我不知道这是不是一个正确的方向。

 **Stein**: 很早的时候我就对数学感兴趣了，特别地，Dickson关于初等数论的书,《数的理论导引》(*Introduction to the Theory of Numbers*)
给我很深的印象。所以芝加哥大学也给我很深刻的印象，而我也想远离我的家。之后他们收了我。

**DeGroot**: 我听你说在你刚读大学的时候，Graves影响了你。你认为还有谁在你事业发展期间给了你主要影响？

**Stein**: 好，毫无疑问，Mac Lane让我觉得代数室重要，即使我从来都没有学好代数。Albert的工作更有技术性，确实也做得非常好，但我是一个懒惰的大学生，但比起其他学生，我对接受抽象更有准备。所以所有科目的第一学季我都做得很好，然后我会感到迷失，因为我没有尽力。

**DeGroot**: 你离开芝加哥大学之后呢？之后，直到现在，还有别的人对你的事业有影响吗？

**Stein**: 嗯，绝对是Neyman和Wald。我在芝加哥读研究生的头两个学季开始了解Neyman在统计方面的工作。那时候我还不知道Wald的工作，但Murray Geisler或者Kenneth Arrow在哥伦比亚就知道Wald了，因为Wald会坐在Hotelling的课堂上，好像看了剧本一样，知道Hotelling接下来要怎样讲。[笑]然后我开始对Wald在序列化分析(sequential analysis)方面的工作感兴趣。他对我帮助很大。他鼓励我，那些日子我偶尔会写信，他给了我很多鼓励和回信。

**DeGroot**: 那是你在空军时候的事情？

**Stein**: 是的。

**DeGrood**: 这就是你对两阶段过程感兴趣的因由吗？

**Stein**: 是的，我对此感兴趣是因为Arrow把Wald关于序列分析的保密论文借给了我，并问我有何看法，论文有何要点。Wald没有取得权只依赖于均值之差而不依赖于方差情况下t测试的序列化版本，他对此表示失望。所以Kenneth Arrow算是建议我去做这个问题，毕竟他告诉我这是一个严肃的问题。然后我开始思考这个问题，察觉如何解决它。我大约花了一周时期确定我的方法是对的。但它其实是很容易想到的。

尽管我不确定我们是否取得预期的成功，但是和这样一群人工作，依然鼓舞了我。你要知道，这给了我发展的可能性。特别是在战后，我们聚在Asheville等待退役的时候，我们组织了一个非正式的讨论班。我做了一些工作，对Wald的成果作了一些不太重要的扩展，推广到一些严格的测试上。然后Gil Hunt向我指出我其实无意间做了群论的工作。

**DeGroot**: 我知道了。那就是不变性方面著名的Hunt-Stein定理(译者注：原文为 Hunt-Stein result 应该是指 [Hunt-Stein theorem](https://www.encyclopediaofmath.org/index.php/Hunt-Stein_theorem))的开端？

**Stein**: 是的。当然很不行这些结果从来没有被出版。它被写在一份后来被弄丢了的手稿上。

**DeGroot**: 被弄丢是什么意思？

**Stein**: 我认为它已经遗失了。让我想想。事情是这样的。对于简单问题，所有的不变过程都有常量风险，讨论最佳不变过程是有意思的，我们着手证明它必须是极小极大值(minimax)。我们小心翼翼以至于我们发现我们没法证明这个命题。[笑]所以Gil和我最后发现对阿贝尔群(可交换群)它是真的，对紧群(译者注: [compact group](https://en.wikipedia.org/wiki/Compact_group))是平凡真的(trivally true)。事实上，阿贝尔群上平均的概率我们之前就完成了，特别是Banach和无数其他人。所以无论如何，它对阿贝尔群和紧群都是真的，因此，逐次简化之后，对可解群(译者注: [solvable groups](https://en.wikipedia.org/wiki/Solvable_group))和由阿贝尔群与紧群组合而来的对象都是真的。

我们最终发现我们无法证明命题在二维下对一般线性群成立，最后我发现了一个反例。但是这个反例拖得太久了，所以论文也拖了很久，所以它最终没有完成。不久之后，我认为，Peisakoff在普林斯顿沿着Tukey的方向研究这个问题。我有点吃惊，因为这个问题太抽象了，而Tukey的兴趣在数理统计上。而Peisakoff为带两个生成元的自由群找到了一个反例。当然，所有这些都被其他数学家做过了，几乎同时。甚至更早一点。你知道，*几乎*是相同的东西。但我想Peisakoff认为他为一般线性群找到了一个证明。

**DeGroot**: 他觉得他有一个证明而你有一个反例。

**Stein**: 是啊。而且，这个反例非常简单。

## “我总是先证明相容性”

**DeGroot**: 看上去这就是我所知道的Charles Stein传统的开端。给大家都信以为真的东西找反例。还有就是搞了一大堆有趣的东西但是不发表。你觉得这个描述精确吗，它至少描述了你的事业的某些方面吧。

**Stein**: 对。这是懒惰和和某种不好的完美主义的结果。无法做到满意就无法完成工作。

**DeGroot**: 其他方面呢？比如说找到启发性的反例的创意？

**Stein**: 是的，举例往往很有用。很自然地，如果这些例子很显然那就更好了。

**DeGroot**: 你在工作中会倾向优先考虑反例吗，还是会先证明一些结论，等遇到过不去的地方再回头找反例？

**Stein**: 后者，我会非常努力去证明大部分结果。

**DeGroot**: 举例来说，对不相容的结果，你会怎样处理？

**Stein**: 哦，是这样的，我总会先证明相容性。有几种形式。其中之一是离散形式，这种情况下，有限维变换群操作在多维位置参数估计问题中是可传递的，我尝试了很久去证明最佳不变过程——Pitman估计——是相容的。可能是在Jimmie Savage的建议下，我最后放弃了这个想法，尝试去证明相反的结论，发现这是很简单的。就是，用Lehmann和Hodges处理一维情形时相同的手法，和正交不变性放在一起考虑，很容易就能证明正态条件下，二维的相容性。尝试将这种方法应用到三维或者更高的维数的时候，我们很清楚这种方法无效了。然后又过了很长一段时间，可能是在Jimmie Savage的刺激下，我意识到既然这个方法显然没有用，而且没办法让它变得可用[待推敲]，那也许就是不相容的。然后是更抽象的形式：如果你有两个完全独立的决策问题而你把损失相加，对这两个问题你各有一个相容过程，我们推断你把两个过程组合在一起得到的对组合之后的问题相容的过程。而这当然不对，因为如果你将二维相容过程和一维估计组合在一起，结果对组合后的问题是不相容的。所以我们对这个推论有了一个反例。我不知道是否有人比我更早想到这个反例。

**DeGroot**: 当我们讨论你的研究时，你有没有一些论文，即使时没有发表过的，你特别喜欢，或者认为特别重要，或者对相关领域有影响的？

**Stein**: 啊，这很难说。我希望从长远来看，我从第六次伯克利研讨会(Sixth Berkeley Symposium)的文章开始的关于正态逼近的想法会比其他的更重要["A bound for the error in the normal approximation to the distribution of a sum of dependent random variables, " *Proc. Sixth Berkeley Symp. Math. Statist. Probab. 2 (1972) 583-602*]. Barbour和Eagleson几年前写了一篇在图论中应用的文章。[Barbour, A. D. and Eagleson, G. K. "Poisson approximation for some statistics based on exchangeable trials," *Adv. Appl. Prob.* 15 (1983) 585-600] 然后Hall和Barbour写了一篇。[Hall, P. and Barbour, A. D. "Reversing the Berry Esseen inequality," *Proc. Amer. Math. Soc*. 90 (1984) 107-110]

**DeGroot**: 这篇论文是从你教的课程中形成的吗？

**Stein**: 嗯，我曾经做过几次讲座。但是效果不如预期。但现在我认为我理解了基础概念，可以阐述它，即使我对它的应用并不是很了解。应用方面变得很混乱。还有几个人用了这个结果——Erickson [Erickson, R.V. "$L_1$ bounds for asymptotic normality of m-dependent sums using Stein's technique, " *Ann. Probab. * 2  (1974) 522-529] 还有一些在法国的人， 还有一些人我不记得了。

**DeGroot**: 而你认为这个想法有北广泛应用的潜力？

**Stein**: 是的，但是在概率论方面，不是在统计方面。


## “贝叶斯观点经常与一种顽见相伴：人们应该同意某种学说尽管他并不清楚这种学说是什么”
**DeGroot**: 你认为概率论和统计之间有清楚的分界吗？

**Stein**: 有的。我在统计方面的工作是相当狭义的数理统计。就说，我们大部分情况下会以决策论的方式思考问题。所以我认为和概率论很不同，尽管很多统计工作其实就是概率论直接的应用，而你也可以把对事物分布的思考结果用到统计学家感兴趣的地方去。但当然，那些超出了我在第六次伯克利研讨会的工作的方法并不是思考概率的唯一之途[待推敲]。特别地，统计问题里面往往有一些问题，与一些带参结构有关，这些结构，因为决策论和别的原因的缘故，用了先验概率来求结果，但是不在贝叶斯哲学框架里面。

**DeGroot**: 既然你提到了，你对贝叶斯哲学框架的看法是怎样的？

**Stein**: 嗯，相当负面。当然有人基于这种观点做出了很多好工作。但基本来说，贝叶斯观点经常与一种顽见相伴：人们应该同意某种学说，尽管他并不真的清楚这种学说是什么。举例来说，你可以告诉我，你认为我们喜闻乐见的贝叶斯观点的权威表示是什么？

**DeGroot**: 哎呀，不是采访我啊。[笑]我可以在我关于贝叶斯决策论的书里面加一节概率和效用理论的公理系统，同时强调整个决策过程(decision-making processs)。我是指，某种程度的规范化。

**Stein**: 对，但这就是关键。人会在知道这东西到底是什么之前就被要求规范化地接受它，而不是其他的系统那样，我们设定好公理或定义然后用它们来扩展成一个系统，*然后*如果这个系统有趣，我们就继续研究。但我们从来不问这些公理是不是真的；相反，我们会问，有没有让我们公理扩展工作显得很有用的例子。如果有，我们就接受这个扩展。特别地，我们尝试去判断结果。然而，你也知道，因为很难选择一个先验概率，所以很难将贝叶斯概念用于一些有趣的问题。Jeffreys提出一个观点，他好像说，有一套方法，他没有搞出来但是愿意证明有效，可以用来选择(通常是不合适的)先验概率，而*这套方法*通常没有用。另一种方法就是主观地选一个先验概率，而我觉得这完全不合理。那好，还有什么好说的呢？统计决策理论给我们一个指示先验概率是如果从另外的观点中进入统计的，当然还留着一些问题。所以在某些程度上，Wald的决策论方法和贝叶斯方法之间的差异是很小的。

**DeGroot**: 因为Wald把先验概率用作确定最优化过程的技术手段。

**Stein**: 对，所以我们在考虑相同的过程。粗略地说，决策论的基本定理说，在某种意义上，好的过程和贝叶斯过程都是非常相似的。这，当然，一个显然的简化，但它使得我们可以理解先验分布是如何进来的。
